create database videogames;

create table videogames.game
(
    id tinyint PRIMARY KEY auto_increment,
    title varchar(255) not null, 
    description text, 
    release_date date not null, 
    poster varchar(255), 
    price decimal (5,2)
);

INSERT INTO `game` (`id`, `title`, `description`, `release_date`, `poster`, `price`) VALUES
(1, 'Mario Bros.', '<p>\n<b>Genre</b>: Platform <br/>\n<b>Platforms</b>: Game Boy Advance\n</p>\n<p>\nA remake of Mario Bros. is included in every Super Mario Advance game, as well as Mario & Luigi: Superstar Saga. All of these games can connect to each other to play Classic or Battle mode with up to four players. Classic is based on the co-op mode from the original and uses the Japanese arcade phase system. Battle is based on the Battle Game from Super Mario All-Stars. The remake also uses the GBA\'s Single-Pak multiplayer feature. It can connect and play with other GBA systems without the game, although Battle is the only multiplayer mode that can be played in this way.\n</p>\n<p>\nThe GBA remake of Mario Bros. enhances the graphics to take advantage of the GBA\'s 32-bit capabilities, including adding backgrounds to the stages. It also adds new movement options and better aerial controls.\n</p>', '1983-05-01', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4wf6.png', '30.50'),
(2, 'Mass Effect Trilogy', '<p><b>Genre</b>: Role-playing (RPG), Shooter\n<br/>\n<b>Platforms</b>: Xbox 360, PlayStation 3\n<br/></p><p>\nExperience all three award winning Mass Effect titles at an amazing value with the Mass Effect Trilogy, coming November 9th. </p>\n<p>\nAs Commander Shepard, rise to become the galaxy’s most elite soldier and lead an all-out war to stop an ancient and ruthless enemy: the Reapers. With over 75 hours of content and more than 300 awards, one of gaming’s most acclaimed franchises is available for the first time in a premium foiled box set.\n</p><p>\nHeart-pounding action meets gripping interactive storytelling where you decide how your unique story unfolds. Assemble and lead your team aboard the SSV Normandy, the most advanced ship in the galaxy, and travel to distant and unexplored star systems. On your journey, meet a cast of intriguing characters each with their own story to tell. Wield devastating weapons and customize them with upgrades to create new and devastating attacks. All the thrilling action and your decisions culminate into a heroic battle against the greatest threat ever known.\n</p><p>\nThe fate of the galaxy lies in your hands—how will you chose to fight for it?\n</p>', '2012-12-04', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4a7a.png', '60.00'),
(3, 'A Plague Tale', '<p><b>Genre</b>: Adventure, Role-playing (RPG)\n<br/>\n<b>Platforms</b>: Xbox One, PlayStation 4, PlayStation 5, PC (Microsoft Windows), Xbox Series X|S\n</p>\n<p>\nA Plague Tale: Innocence, on PlayStation 4, Xbox One and PC, tells the grim story of two siblings fighting together for survival in the darkest hours of History. This new video game from Asobo Studio sends you on an emotional journey through the 14th century France, with gameplay combining adventure, action and stealth, supported by a compelling story. Follow the young Amicia and her little brother Hugo, who face the brutality of a ravaged world as they discover their purpose to expose a dark secret. On the run from the Inquisition\'s soldiers, surrounded by unstoppable swarms of rats incarnating the Black Death, Amicia and Hugo will learn to know and trust each other as they struggle for their lives against all odds.\n</p>', '2019-08-05', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1lat.png', '39.99'),
(4, 'Metro Exodus', '<p><b>Genre</b>: Adventure, Shooter </br>\n<b>Platforms</b>: Xbox One, PlayStation 4, PlayStation 5, PC (Microsoft Windows), Xbox Series X|S, Google Stadia\n</p>\n<p>\nMetro Exodus is an epic, story-driven first person shooter from 4A Games that blends deadly combat and stealth with exploration and survival horror in one of the most immersive game worlds ever created. Explore the Russian wilderness across vast, non-linear levels and follow a thrilling story-line that spans an entire year through spring, summer and autumn to the depths of nuclear winter. Inspired by the novels of Dmitry Glukhovsky, Metro Exodus continues Artyom’s story in the greatest Metro adventure yet.\n</p>', '2019-04-09', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1iuj.png', '30.99'),
(5, 'The Legend of Zelda Ocarina of Time 3D: First Edition', '<p><b>Genre</b>: Adventure, Role-playing (RPG)</br>\n<b>Platforms</b>: Nintendo 3DS\n</p>\n<p>The First Edition of The Legend of Zelda Ocarina of Time 3D is identical to the standard edition except that it included a bonus case as well as a poster.\n</p>', '2011-06-11', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3koo.png', '30.99'),
(6, 'Limbo', '<p>\n<b>Genre</b>: Adventure, Indie, Platform, Puzzle </br>\n<b>Platforms</b>: Android, Xbox One, PlayStation 4, Linux, Xbox 360, Mac, iOS, PlayStation Vita, PC (Microsoft Windows), Nintendo Switch, PlayStation 3\n</p>\n<p>\nLimbo is a black and white puzzle-platforming adventure. Play the role of a young boy traveling through an eerie and treacherous world in an attempt to discover the fate of his sister.\nLimbo is a black and white puzzle-platforming adventure. Play the role of a young boy traveling through an eerie and treacherous world in an attempt to discover the fate of his sister.\n</p>', '2010-06-21', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1qrs.png', '19.95'),
(7, 'Street Fighter IV', '<p>\n<b>Genre</b>: Fighting </br>\n\n<b>Platforms</b>: Android, Xbox 360, iOS, Arcade, PC (Microsoft Windows), PlayStation 3\n</br>\n<b>Editions</b>: See 2 more editions of this game\n</p>\n\n<p>\nStreet Fighter IV brings the legendary fighting series back to its roots by taking the beloved fighting moves and techniques of the original Street Fighter II, and infusing them with Capcom’s latest advancements in next generation technology to create a truly extraordinary experience that will re-introduce the world to the time-honored art of virtual martial arts.\n<p>\n<p>\nNewcomers:</br>\n- Abel</br>\n- C.Viper</br>\n- Rufus</br>\n- El Fuerte</br>\n- Gouken</br>\n</p>', '2008-06-18', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1w4t.png', '25.50'),
(8, 'Death Stranding', '<p>\n<b>Genre</b>: Adventure, Role-playing (RPG), Shooter </br>\n<b>Platforms</b>: PlayStation 4, PC (Microsoft Windows)</br>\n<b>Editions</b>: See 3 more editions of this game\n</p>\n<p>\nFrom legendary game creator Hideo Kojima comes an all-new, genre-defying open world action adventure, starring Norman Reedus, Mads Mikkelsen, Léa Seydoux and Lindsay Wagner.\n</p>\n<p>\nIn the near future, mysterious explosions have rocked the globe, setting off a series of supernatural events known as the Death Stranding. With otherworldly creatures plaguing the landscape, and mass extinction imminent, it’s up to Sam Porter Bridges to travel across the ravaged wasteland and save humanity from impending annihilation.\n</p>', '2019-10-08', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5vq8.png', '30.99');


/* Partie authentification */

create table videogames.admin
(
	id tinyint unsigned PRIMARY KEY auto_increment,
	email varchar(100) unique, 
	password varchar(100)
)

insert into videogames.admin(email, password)
values ("admin@hitema.fr","b2647a7e9b8592254f7b2d86790263ac");  
